name: pet-noise-radiomics
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-image
  - scikit-learn
  - matplotlib
  - pydicom
  - simpleitk
  - pip
  - pip:
      - pyradiomics
